# Calibration, Rectification, and Keypoints Detection

In [1]:
import cv2
from numpy import *
import numpy as np
import os

## Defining paths

In [2]:
path_R = "./captured/both/right/" #L
path_L = "./captured/both/left/" #R

calib_params = "./captured/calibrators/calibParams/"

## Reading the images and saving them into respective lists

In [3]:
'''READING IMAGES FROM FILE AND SORTING THEM'''
# listings_L = os.listdir(path_L)
# size_L = size(listings_L)
# listings_R = os.listdir(path_R)
# size_R = size(listings_R)

size_L = size(os.listdir(path_L))
size_R = size(os.listdir(path_R))

number_of_images = 0
if size_L == size_R:
    number_of_images = size_L
#endif

offset = 0
listings_L, listings_R = [], []
for i in range(offset+0, offset+number_of_images):
    listings_L.append(f'{i}_L_.png')
    listings_R.append(f'{i}_R_.png')
#endfor

print(size_L,size_R)
print(listings_L)
print()
print(listings_R)

61 61
['0_L_.png', '1_L_.png', '2_L_.png', '3_L_.png', '4_L_.png', '5_L_.png', '6_L_.png', '7_L_.png', '8_L_.png', '9_L_.png', '10_L_.png', '11_L_.png', '12_L_.png', '13_L_.png', '14_L_.png', '15_L_.png', '16_L_.png', '17_L_.png', '18_L_.png', '19_L_.png', '20_L_.png', '21_L_.png', '22_L_.png', '23_L_.png', '24_L_.png', '25_L_.png', '26_L_.png', '27_L_.png', '28_L_.png', '29_L_.png', '30_L_.png', '31_L_.png', '32_L_.png', '33_L_.png', '34_L_.png', '35_L_.png', '36_L_.png', '37_L_.png', '38_L_.png', '39_L_.png', '40_L_.png', '41_L_.png', '42_L_.png', '43_L_.png', '44_L_.png', '45_L_.png', '46_L_.png', '47_L_.png', '48_L_.png', '49_L_.png', '50_L_.png', '51_L_.png', '52_L_.png', '53_L_.png', '54_L_.png', '55_L_.png', '56_L_.png', '57_L_.png', '58_L_.png', '59_L_.png', '60_L_.png']

['0_R_.png', '1_R_.png', '2_R_.png', '3_R_.png', '4_R_.png', '5_R_.png', '6_R_.png', '7_R_.png', '8_R_.png', '9_R_.png', '10_R_.png', '11_R_.png', '12_R_.png', '13_R_.png', '14_R_.png', '15_R_.png', '16_R_.png

In [4]:
imgL_list = []
imgR_list = []

i = 0
while(i<size_L):
    imL = cv2.imread(path_L+listings_L[i], 0)
    imgL_list.append(imL)
    i+=1
#endwhile

i = 0
while(i<size_R):
    imR = cv2.imread(path_R+listings_R[i], 0)
    imgR_list.append(imR)
    i+=1
#endwhile

import random
temp = list(zip(imgL_list, imgR_list))
random.shuffle(temp)
imgL_list, imgR_list = zip(*temp)
print(len(imgR_list), len(imgL_list))

61 61


In [5]:
imgR_list[17]

array([[230, 228, 235, ...,  10,  15,   9],
       [236, 234, 239, ...,  11,  12,  13],
       [228, 237, 234, ...,  14,  13,  12],
       ...,
       [ 69,  80,  63, ...,  29,  29,  27],
       [ 72,  66,  74, ...,  18,  23,  33],
       [ 76,  66,  69, ...,  18,  35,  21]], dtype=uint8)

## Detection of chessboard points
Reference -> https://stackoverflow.com/questions/37310210/camera-calibration-with-opencv-how-to-adjust-chessboard-square-size

In [6]:
'''CALIBRATING STARTS HERE'''
img_left_points = []
img_right_points = []
obj_points = []
size = size_L

h, w = 9, 6
pattern_size = (h,w)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((w*h,3), np.float32)
objp[:,:2] = np.mgrid[0:h,0:w].T.reshape(-1,2)*24.5
print(objp)

[[  0.    0.    0. ]
 [ 24.5   0.    0. ]
 [ 49.    0.    0. ]
 [ 73.5   0.    0. ]
 [ 98.    0.    0. ]
 [122.5   0.    0. ]
 [147.    0.    0. ]
 [171.5   0.    0. ]
 [196.    0.    0. ]
 [  0.   24.5   0. ]
 [ 24.5  24.5   0. ]
 [ 49.   24.5   0. ]
 [ 73.5  24.5   0. ]
 [ 98.   24.5   0. ]
 [122.5  24.5   0. ]
 [147.   24.5   0. ]
 [171.5  24.5   0. ]
 [196.   24.5   0. ]
 [  0.   49.    0. ]
 [ 24.5  49.    0. ]
 [ 49.   49.    0. ]
 [ 73.5  49.    0. ]
 [ 98.   49.    0. ]
 [122.5  49.    0. ]
 [147.   49.    0. ]
 [171.5  49.    0. ]
 [196.   49.    0. ]
 [  0.   73.5   0. ]
 [ 24.5  73.5   0. ]
 [ 49.   73.5   0. ]
 [ 73.5  73.5   0. ]
 [ 98.   73.5   0. ]
 [122.5  73.5   0. ]
 [147.   73.5   0. ]
 [171.5  73.5   0. ]
 [196.   73.5   0. ]
 [  0.   98.    0. ]
 [ 24.5  98.    0. ]
 [ 49.   98.    0. ]
 [ 73.5  98.    0. ]
 [ 98.   98.    0. ]
 [122.5  98.    0. ]
 [147.   98.    0. ]
 [171.5  98.    0. ]
 [196.   98.    0. ]
 [  0.  122.5   0. ]
 [ 24.5 122.5   0. ]
 [ 49.  122.5

In [7]:
j=0
while(j<size):
    print(j)
    image_size = imgL_list[j].shape
    find_chessboard_flags = cv2.CALIB_CB_ADAPTIVE_THRESH | cv2.CALIB_CB_NORMALIZE_IMAGE | cv2.CALIB_CB_FAST_CHECK

    left_found, left_corners = cv2.findChessboardCorners(imgL_list[j], pattern_size, flags = find_chessboard_flags)
    right_found, right_corners = cv2.findChessboardCorners(imgR_list[j], pattern_size, flags = find_chessboard_flags)
 
    if left_found:
        cv2.cornerSubPix(imgL_list[j], left_corners, (11,11), (-1,-1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1))
    if right_found:
        cv2.cornerSubPix(imgR_list[j], right_corners, (11,11), (-1,-1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1))
 
    if left_found and right_found:
        img_left_points.append(left_corners)
        img_right_points.append(right_corners)
        obj_points.append(objp)

    #cv2.imshow("left", imgL_list[j])q 
    cv2.drawChessboardCorners(imgL_list[j], pattern_size, left_corners, left_found)
    cv2.drawChessboardCorners(imgR_list[j], pattern_size, right_corners, right_found)
    #cv2.waitKey(300)
    cv2.imshow("r chess", cv2.resize(imgR_list[j], (640,480)))
    cv2.imshow("l chess", cv2.resize(imgL_list[j], (640,480)))
    cv2.waitKey(500)
    j+=1
#endwhile
cv2.destroyAllWindows()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60


In [8]:
cv2.destroyAllWindows()

In [9]:
len(img_left_points)

57

In [10]:
imL.shape[:2]

(1200, 1600)

In [11]:
imL.shape[::-1]

(1600, 1200)

## Calibrating the cameras on the basis of chessboard points

In [12]:
# Determine the new values for different parameters
#   Right Side
retR, mtxR, distR, rvecsR, tvecsR = cv2.calibrateCamera(obj_points,
                                                        img_right_points,
                                                        imR.shape[::-1],None,None)
hR,wR = imR.shape[:2]
OmtxR, roiR= cv2.getOptimalNewCameraMatrix(mtxR,distR,
                                                   (wR,hR),1,(wR,hR))

#   Left Side
retL, mtxL, distL, rvecsL, tvecsL = cv2.calibrateCamera(obj_points,
                                                        img_left_points,
                                                        imL.shape[::-1],None,None)
hL,wL = imL.shape[:2]
OmtxL, roiL = cv2.getOptimalNewCameraMatrix(mtxL,distL,(wL,hL),1,(wL,hL))

print('Cameras Ready to use')

Cameras Ready to use


In [13]:
print('mean reprojection error - right: ', retR)
print('mean reprojection error - left: ', retL)

print("roiR: ", roiR)
print("roiL: ", roiL)

mean reprojection error - right:  1.0766688996804756
mean reprojection error - left:  0.8365157029525241
roiR:  (353, 170, 907, 843)
roiL:  (359, 169, 931, 846)


In [14]:
img = imR.copy()
# using cv2.undistort
dst = cv2.undistort(img, mtxR, distR, None, OmtxR)
x,y,w,h = roiR
dst = dst[y:y+h, x:x+w]

# using remapping
right_map = cv2.initUndistortRectifyMap(mtxR, distR, None, OmtxR, img.shape[::-1], cv2.CV_16SC2)
rdst = cv2.remap(img,right_map[0],right_map[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
x,y,w,h = roiR
rdst = rdst[y:y+h, x:x+w]

cv2.imshow('undist', cv2.resize(dst, (640,480)))
cv2.imshow('rundist', cv2.resize(rdst, (640,480)))
cv2.imshow('img', cv2.resize(img, (640,480)))
cv2.waitKey(0)
cv2.destroyAllWindows()

#cv2.imwrite('./undist.png', dst)
#cv2.imwrite('./rundist.png', rdst)
#cv2.imwrite('./img.png', img)

In [15]:
cv2.destroyAllWindows()

In [16]:
print(roiR)
print(roiL)

(353, 170, 907, 843)
(359, 169, 931, 846)


In [17]:
formatm = [["fx","0","cx"],["0","fy","cy"],["0","0","1"]]
print('\n format -> \n',formatm)
print('\n mtxR -> \n',mtxR,2*'\n','OmtxR -> \n',OmtxR,2*'\n','mtxL -> \n',mtxL,2*'\n','OmtxL -> \n',OmtxL)


 format -> 
 [['fx', '0', 'cx'], ['0', 'fy', 'cy'], ['0', '0', '1']]

 mtxR -> 
 [[868.37201109   0.         810.36308916]
 [  0.         862.78306168 594.25535866]
 [  0.           0.           1.        ]] 

 OmtxR -> 
 [[492.20748901   0.         811.87689625]
 [  0.         606.27728271 587.55357665]
 [  0.           0.           1.        ]] 

 mtxL -> 
 [[880.07697126   0.         803.24183072]
 [  0.         880.18729834 596.5114081 ]
 [  0.           0.           1.        ]] 

 OmtxL -> 
 [[512.04510498   0.         826.11342001]
 [  0.         620.84625244 589.85326051]
 [  0.           0.           1.        ]]


In [21]:
# Termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
criteria_stereo = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.001)

# StereoCalibrate function
# flags = 0
# flags |= cv2.CALIB_FIX_INTRINSIC
# flags |= cv2.CALIB_FIX_PRINCIPAL_POINT
# flags |= cv2.CALIB_USE_INTRINSIC_GUESS
# flags |= cv2.CALIB_FIX_FOCAL_LENGTH
# flags |= cv2.CALIB_FIX_ASPECT_RATIO
# flags |= cv2.CALIB_ZERO_TANGENT_DIST
# flags |= cv2.CALIB_RATIONAL_MODEL
# flags |= cv2.CALIB_SAME_FOCAL_LENGTH
# flags |= cv2.CALIB_FIX_K3
# flags |= cv2.CALIB_FIX_K4
# flags |= cv2.CALIB_FIX_K5
flags = cv2.CALIB_FIX_ASPECT_RATIO | cv2.CALIB_ZERO_TANGENT_DIST | cv2.CALIB_SAME_FOCAL_LENGTH | cv2.CALIB_RATIONAL_MODEL | cv2.CALIB_FIX_K3 | cv2.CALIB_FIX_K4 | cv2.CALIB_FIX_K5
#flags = cv2.CALIB_FIX_INTRINSIC
retS, MLS, dLS, MRS, dRS, R, T, E, F = cv2.stereoCalibrate(obj_points,
                                                          img_left_points,
                                                          img_right_points,
                                                          mtxL,
                                                          distL,
                                                          mtxR,
                                                          distR,
                                                          imR.shape[::-1],
                                                          criteria_stereo,
                                                          flags)


In [22]:
print('mean reprojection error: ', retS)
print(' MRS -> ',MRS,2*'\n','mtxR -> ',mtxR,2*'\n','MLS -> ',MLS,2*'\n','mtxL -> ',mtxL)

mean reprojection error:  1.2968537770583775
 MRS ->  [[868.37201109   0.         810.36308916]
 [  0.         862.78306168 594.25535866]
 [  0.           0.           1.        ]] 

 mtxR ->  [[868.37201109   0.         810.36308916]
 [  0.         862.78306168 594.25535866]
 [  0.           0.           1.        ]] 

 MLS ->  [[880.07697126   0.         803.24183072]
 [  0.         880.18729834 596.5114081 ]
 [  0.           0.           1.        ]] 

 mtxL ->  [[880.07697126   0.         803.24183072]
 [  0.         880.18729834 596.5114081 ]
 [  0.           0.           1.        ]]


In [23]:
print(' Rotational -> \n',R,2*'\n','Translational -> \n',T,2*'\n','Essential -> \n',E,2*'\n','Fundamental -> \n',F)
# Rotational Translational Essential Fundamental

 Rotational -> 
 [[ 0.99987344  0.00912293 -0.01303375]
 [-0.00947706  0.9995804  -0.02737168]
 [ 0.01277857  0.02749174  0.99954035]] 

 Translational -> 
 [[297.85296464]
 [  1.16534976]
 [ -7.9825853 ]] 

 Essential -> 
 [[-6.07599091e-02  8.01127329e+00  9.46317338e-01]
 [-1.17877107e+01 -8.26132000e+00 -2.97612014e+02]
 [-3.98797179e+00  2.97717354e+02 -8.13754710e+00]] 

 Fundamental -> 
 [[ 9.44979556e-09 -1.24581170e-06  6.06022690e-04]
 [ 1.84518100e-06  1.29301781e-06  3.87462679e-02]
 [-5.65570378e-04 -3.99620417e-02  1.00000000e+00]]


In [24]:
np.save(calib_params+'R.npy', R)
np.save(calib_params+'T.npy', T)
np.save(calib_params+'E.npy', E)
np.save(calib_params+'F.npy', F)

np.save(calib_params+'MLS.npy', MLS)
np.save(calib_params+'dLS.npy', dLS)
np.save(calib_params+'MRS.npy', MRS)
np.save(calib_params+'dRS.npy', dRS)

## Rectifying params through which captured images can be rectified accordingly

In [25]:
# StereoRectify function
rectify_scale = 1# if 0 image croped, if 1 image nor croped
RL, RR, PL, PR, Q, roiL, roiR = cv2.stereoRectify(MLS, dLS, MRS, dRS,
                                                 imR.shape[::-1], R, T,
                                                 rectify_scale) # last paramater is alpha, if 0= croped, if 1= not croped
# initUndistortRectifyMap function
Left_Stereo_Map = cv2.initUndistortRectifyMap(MLS, dLS, RL, PL,
                                             imR.shape[::-1], cv2.CV_16SC2)   # cv2.CV_16SC2 this format enables us the programme to work faster
Right_Stereo_Map = cv2.initUndistortRectifyMap(MRS, dRS, RR, PR,
                                              imR.shape[::-1], cv2.CV_16SC2)
#*******************************************
#***** Parameters for the StereoVision *****
#*******************************************

In [26]:
np.save(calib_params+'RL.npy', RL)
np.save(calib_params+'RR.npy', RR)
np.save(calib_params+'PL.npy', PL)
np.save(calib_params+'PR.npy', PR)

np.save(calib_params+'Q.npy', Q)

In [27]:
print(roiR)
print(roiL)

(8, 24, 1592, 1176)
(15, 0, 1573, 1146)


In [28]:
Q

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -8.60201920e+02],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -5.94928680e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.71485180e+02],
       [ 0.00000000e+00,  0.00000000e+00, -3.35613049e-03,
         0.00000000e+00]])

## Reading the images to get them rectified

In [ ]:
pic_num = '1'
rect_path = "./captured/rectified/"
frameL = cv2.imread(path_L+pic_num+'_L_.png')
frameR = cv2.imread(path_R+pic_num+'_R_.png')

Left_nice = cv2.remap(frameL,Left_Stereo_Map[0],Left_Stereo_Map[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)  # Rectify the image using the kalibration parameters founds during the initialisation
Right_nice = cv2.remap(frameR,Right_Stereo_Map[0],Right_Stereo_Map[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)

In [ ]:
def draw_lines(img):
    y,count = 0,0
    while(count<40):
        img = cv2.line(img, (0,50+y), (img.shape[1],50+y), (y,count*2,y), 2)
        y+=30
        count+=1
    #endwhile
    return cv2.resize(img, (640,480))
#enddef

chairL = frameL.copy()
chairR = frameR.copy()

xr,yr,wr,hr = roiR
xl,yl,wl,hl = roiL

#Right_nice = Right_nice[yl:yl+hr, xr:xr+wr]
#Left_nice = Left_nice[yl:yl+hr, xl:xl+wl]

right_img_remap_copy = Right_nice.copy()
left_img_remap_copy = Left_nice.copy()
'''
y,count = 0,0
while(count<40):
    chairR = cv2.line(chairR, (0,50+y), (1280,50+y), (0,count*2,y), 2)
    chairL = cv2.line(chairL, (0,50+y), (1280,50+y), (0,count*2,y), 2)
    right_img_remap_copy = cv2.line(right_img_remap_copy, (0,50+y), (1280,50+y), (0,count*2,y), 2)
    left_img_remap_copy = cv2.line(left_img_remap_copy, (0,50+y), (1280,50+y), (0,count*2,y), 2)
    y+=30
    count+=1
'''   
cv2.imshow('R', draw_lines(chairR))
cv2.imshow('L', draw_lines(chairL))
cv2.imshow('R rect', draw_lines(right_img_remap_copy))
cv2.imshow('L rect', draw_lines(left_img_remap_copy))
cv2.waitKey(0)

origLR = np.concatenate((chairL, chairR), axis=1)
cv2.imwrite(rect_path+pic_num+'_orig.png', origLR)
rectLR = np.concatenate((left_img_remap_copy, right_img_remap_copy), axis=1)
cv2.imwrite(rect_path+pic_num+'_rect.png', rectLR)
cv2.destroyAllWindows()

In [ ]:
cv2.destroyAllWindows()

## Depth Map using WLS Filtering

In [ ]:
grayR = cv2.cvtColor(Right_nice,cv2.COLOR_BGR2GRAY)
grayL = cv2.cvtColor(Left_nice,cv2.COLOR_BGR2GRAY)

# Create StereoSGBM and prepare all parameters
window_size = 7
min_disp = 1
num_disp = (16*16)+1-min_disp
left_matcher = cv2.StereoSGBM_create(minDisparity = min_disp,
    numDisparities = num_disp,
    blockSize = window_size,
    uniquenessRatio = 10,
    speckleWindowSize = 100,
    speckleRange = 32,
    disp12MaxDiff = 5,
    P1 = 8*3*window_size**2,
    P2 = 32*3*window_size**2)

# Used for the filtered image
right_matcher = cv2.ximgproc.createRightMatcher(left_matcher) # Create another stereo for right this time

# WLS FILTER Parameters
lmbda = 80000
sigma = 1.8
visual_multiplier = 1.0
 
wls_filter = cv2.ximgproc.createDisparityWLSFilter(matcher_left=left_matcher)
wls_filter.setLambda(lmbda)
wls_filter.setSigmaColor(sigma)

dispL = left_matcher.compute(grayL,grayR)
dispR = right_matcher.compute(grayR,grayL)
dispL = np.int16(dispL)
dispR = np.int16(dispR)

filteredImg = wls_filter.filter(dispL, grayL, None, dispR)  # important to put "imgL" here!!!
filteredImg = cv2.normalize(src=filteredImg, dst=filteredImg, beta=0, alpha=255, norm_type=cv2.NORM_MINMAX);
filteredImg = np.uint8(filteredImg)

fil = cv2.resize(filteredImg, (1920,1080))
cv2.imshow('filteredImg',fil)
cv2.waitKey(0)
cv2.destroyAllWindows()
# plt.imshow(cv2.cvtColor(fil, cv2.COLOR_GRAY2RGB))
# plt.show()

In [ ]:
cv2.destroyAllWindows()

In [ ]:
print(Left_nice.shape, Right_nice.shape)

## Impixelinfo

In [ ]:
%matplotlib notebook
import matplotlib
import matplotlib.pyplot as plt

imgs = []
imgs.append(cv2.cvtColor(frameL, cv2.COLOR_BGR2RGB))
imgs.append(cv2.cvtColor(frameR, cv2.COLOR_BGR2RGB))
imgs.append(cv2.cvtColor(Left_nice, cv2.COLOR_BGR2RGB))
imgs.append(cv2.cvtColor(Right_nice, cv2.COLOR_BGR2RGB))

row,col = 2,2
f, axarr = plt.subplots(row,col,figsize=(10,10))
f.tight_layout()

axarr[0,0].imshow(imgs[0]),axarr[0,0].set_title('frameL', color='r', size=15), axarr[0,0].axis('off')
axarr[0,1].imshow(imgs[1]),axarr[0,1].set_title('frameR', color='r', size=15), axarr[0,1].axis('off')

axarr[1,0].imshow(imgs[2]),axarr[1,0].set_title('rectL', color='r', size=15), axarr[1,0].axis('off')
axarr[1,1].imshow(imgs[3]),axarr[1,1].set_title('rectR', color='r', size=15), axarr[1,1].axis('off')

plt.show()

## Calculating disparity

In [ ]:
cv2.namedWindow('disparity_con')
con = np.zeros((500,500,3), np.uint8)

def nothing(x):
    pass

numDisp = 1
highDisp = 30

bS = 1
highBS = 127

# creating trackbars
cv2.createTrackbar('disp', 'disparity_con', numDisp, highDisp, nothing)
cv2.createTrackbar('block', 'disparity_con', bS, highBS, nothing)

while(True):
    # get the trackbar positions and set them to l_h, l_s, l_v respectively
    numDisp = cv2.getTrackbarPos('disp', 'disparity_con')
    bS = cv2.getTrackbarPos('block', 'disparity_con')
    if numDisp == 0:
        numDisp = 1
    if bS == 0:
        bS = 1
    #endif
    cv2.putText(con, 'Disp: '+str(numDisp*16), (150,40),2,1,(255,255,255),1,0)
    cv2.putText(con, 'Block: '+str(2*(bS)+1), (150,70),2,1,(255,255,255),1,0)
    
    stereo = cv2.StereoSGBM_create(1, 16*numDisp, 2*(bS)+1)
    disparity = stereo.compute(Left_nice, Right_nice)
    #disparity = ((disparity.astype(np.float32)/ 16)-1)/numDisp
    #disparity = stereo.compute(origR, origL).astype(np.float32)

    norm_coeff = 255 / disparity.max()
    cv2.imshow("disparity", disparity * norm_coeff / 255)
    #cv2.imshow('disparity', disparity)
    cv2.imshow('disparity_con', con)
    
    con = np.zeros((500,500,3), np.uint8)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break

cv2.destroyAllWindows()
plt.imshow(disparity,'gray')
plt.show()

In [ ]:
cv2.destroyAllWindows()

## Keypoints Detection

In [ ]:
imgL = Left_nice.copy()
imgR = Right_nice.copy()
out_image = None

# Initiate FAST object with default values
fast = cv2.FastFeatureDetector_create() 
sift = cv2.xfeatures2d.SIFT_create()
# find and draw the keypoints
kpL = sift.detect(imgL, None)
img2L = cv2.drawKeypoints(imgL, kpL, out_image, color=(255,0,0))
kpR = sift.detect(imgR, None)
img2R = cv2.drawKeypoints(imgR, kpR, out_image, color=(255,0,0))

#cv2.imshow('kpL', img2L)
#cv2.imshow('kpR', img2R)
#hor = np.hstack((img2L, img2R))
vis = np.concatenate((img2L, img2R), axis=1)
#cv2.imshow('mkp', vis)
#cv2.imwrite('kp.png', vis)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
print(vis.shape)
plt.clf()
plt.imshow(cv2.cvtColor(vis, cv2.COLOR_BGR2RGB), aspect='auto')
plt.show()

In [ ]:
cv2.destroyAllWindows()

In [ ]:
disparity

## Point cloud -> *problematic*

In [ ]:
ply_header = '''ply
format ascii 1.0
element vertex %(vert_num)d
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
'''

def write_ply(fn, verts, colors):
    verts = verts.reshape(-1, 3)
    colors = colors.reshape(-1, 3)
    verts = np.hstack([verts, colors])
    with open(fn, 'wb') as f:
        f.write((ply_header % dict(vert_num=len(verts))).encode('utf-8'))
        np.savetxt(f, verts, fmt='%f %f %f %d %d %d ')
#enddef

disparity = filteredImg.copy()
points = cv2.reprojectImageTo3D(disparity, Q)
colors = cv2.cvtColor(Left_nice, cv2.COLOR_BGR2RGB)
#colors = left_img_remap
mask = disparity > disparity.min()
out_points = points[mask]
out_colors = colors[mask]

#cv2.imshow('left', left_img_remap)
#cv2.imshow('right', right_img_remap)
cv2.imshow('disparity', disparity)
cv2.waitKey(0)
out_fn = 'out_new.ply'
write_ply('out_new.ply', out_points, out_colors)
print('%s saved' % 'out_new.ply')

In [ ]:
cv2.destroyAllWindows()

In [ ]:
disparity.min()

In [ ]:
points

## Testing in real time

#### For Basler cams

In [ ]:
from pypylon import pylon
import cv2
import numpy as np

# Pypylon get camera by serial number
serial_number_1 = '22730679' #right
serial_number_2 = '22730681' #left
cams = []

for i in pylon.TlFactory.GetInstance().EnumerateDevices():
    cams.append(i)
#next

print(cams[0].GetSerialNumber(), cams[1].GetSerialNumber())
camera_1 = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateDevice(cams[0]))
camera_2 = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateDevice(cams[1]))
camera_1.Open()
camera_2.Open()

# Grabing Continusely (video) with minimal delay
camera_1.StartGrabbing(pylon.GrabStrategy_LatestImageOnly) 
camera_2.StartGrabbing(pylon.GrabStrategy_LatestImageOnly) 
converter = pylon.ImageFormatConverter()

# converting to opencv bgr format
converter.OutputPixelFormat = pylon.PixelType_BGR8packed
converter.OutputBitAlignment = pylon.OutputBitAlignment_MsbAligned

while camera_1.IsGrabbing() and camera_2.IsGrabbing():
    grabResult_1 = camera_1.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
    grabResult_2 = camera_2.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)

    if grabResult_1.GrabSucceeded() and grabResult_2.GrabSucceeded():
        # Access the image data
        image_1 = converter.Convert(grabResult_1) #right
        image_2 = converter.Convert(grabResult_2) #left

        frame1 = image_1.GetArray()
        frame2 = image_2.GetArray()

        frame1_gray = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
        frame2_gray = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

        vid_right_nice = cv2.remap(frame1,Right_Stereo_Map[0],Right_Stereo_Map[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
        vid_left_nice = cv2.remap(frame2,Left_Stereo_Map[0],Left_Stereo_Map[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
        
        chairL = frame1_gray.copy()
        chairR = frame2_gray.copy()
        vid_right_nice_copy = vid_right_nice.copy()
        vid_left_nice_copy = vid_left_nice.copy()

        y,count = 0,0
        while(count<40):
            chairR = cv2.line(chairR, (0,50+y), (1920,50+y), (0,count*2,y), 2)
            chairL = cv2.line(chairL, (0,50+y), (1920,50+y), (0,count*2,y), 2)
            vid_right_nice_copy = cv2.line(vid_right_nice_copy, (0,50+y), (1920,50+y), (0,count*2,y), 2)
            vid_left_nice_copy = cv2.line(vid_left_nice_copy, (0,50+y), (1920,50+y), (0,count*2,y), 2)
            y+=30
            count+=1
        #endwhile

        cv2.imshow('right', cv2.resize(chairR, (640,480)))
        cv2.imshow('left', cv2.resize(chairL, (640,480)))

        cv2.imshow('right_nice', cv2.resize(vid_right_nice_copy, (640,480)))
        cv2.imshow('left_nice', cv2.resize(vid_left_nice_copy, (640,480)))

        # saving images into the respective folders
        if cv2.waitKey(1) & 0xff == ord('q'):
            break
        #endif
    #endif
    grabResult_1.Release()
    grabResult_2.Release()
#endwhile
    
# Releasing the resource    
camera_1.StopGrabbing()
camera_2.StopGrabbing()

cv2.destroyAllWindows()