In [1]:
import cv2
from numpy import *
import numpy as np
import os
import random

In [2]:
pathR = "../right/"
pathL = "../left/"

pathStR = "../both/right/"
pathStL = "../both/left/"

calibParams = "./calibParams/"

## Fetching images of individual cam

In [3]:
sizeR = size(os.listdir(pathR))
sizeL = size(os.listdir(pathL))

offset = 0
listingsR = []
for i in range(offset+0, offset+sizeR):
    listingsR.append(f'{i}_R_.png')
#endfor

listingsL = []
for i in range(offset+0, offset+sizeL):
    listingsL.append(f'{i}_L_.png')
#endfor

print(sizeR, sizeL)
print(listingsR, listingsL)

print("\nAfter shuffle:\n")
random.shuffle(listingsR)
random.shuffle(listingsL)
print(listingsR, listingsL)

48 45
['0_R_.png', '1_R_.png', '2_R_.png', '3_R_.png', '4_R_.png', '5_R_.png', '6_R_.png', '7_R_.png', '8_R_.png', '9_R_.png', '10_R_.png', '11_R_.png', '12_R_.png', '13_R_.png', '14_R_.png', '15_R_.png', '16_R_.png', '17_R_.png', '18_R_.png', '19_R_.png', '20_R_.png', '21_R_.png', '22_R_.png', '23_R_.png', '24_R_.png', '25_R_.png', '26_R_.png', '27_R_.png', '28_R_.png', '29_R_.png', '30_R_.png', '31_R_.png', '32_R_.png', '33_R_.png', '34_R_.png', '35_R_.png', '36_R_.png', '37_R_.png', '38_R_.png', '39_R_.png', '40_R_.png', '41_R_.png', '42_R_.png', '43_R_.png', '44_R_.png', '45_R_.png', '46_R_.png', '47_R_.png'] ['0_L_.png', '1_L_.png', '2_L_.png', '3_L_.png', '4_L_.png', '5_L_.png', '6_L_.png', '7_L_.png', '8_L_.png', '9_L_.png', '10_L_.png', '11_L_.png', '12_L_.png', '13_L_.png', '14_L_.png', '15_L_.png', '16_L_.png', '17_L_.png', '18_L_.png', '19_L_.png', '20_L_.png', '21_L_.png', '22_L_.png', '23_L_.png', '24_L_.png', '25_L_.png', '26_L_.png', '27_L_.png', '28_L_.png', '29_L_.png'

In [4]:
imgRList = []
i = 0
while(i<sizeR):
    imR = cv2.imread(pathR+listingsR[i], 0)
    imgRList.append(imR)
    i+=1
#endwhile
print(len(imgRList))

imgLList = []
i = 0
while(i<sizeL):
    imL = cv2.imread(pathL+listingsL[i], 0)
    imgLList.append(imL)
    i+=1
#endwhile
print(len(imgLList))

if len(imgRList) > 0:
    print(imgRList[0].shape)
#endif

if len(imgLList) > 0:
    print(imgLList[0].shape)
#endif

48
45
(1200, 1600)
(1200, 1600)


In [5]:
chessSqSize = 27
h, w = 7, 7
patternSize = (h,w)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((w*h,3), np.float32)
objp[:,:2] = np.mgrid[0:h,0:w].T.reshape(-1,2)*chessSqSize
print(objp)

[[  0.   0.   0.]
 [ 27.   0.   0.]
 [ 54.   0.   0.]
 [ 81.   0.   0.]
 [108.   0.   0.]
 [135.   0.   0.]
 [162.   0.   0.]
 [  0.  27.   0.]
 [ 27.  27.   0.]
 [ 54.  27.   0.]
 [ 81.  27.   0.]
 [108.  27.   0.]
 [135.  27.   0.]
 [162.  27.   0.]
 [  0.  54.   0.]
 [ 27.  54.   0.]
 [ 54.  54.   0.]
 [ 81.  54.   0.]
 [108.  54.   0.]
 [135.  54.   0.]
 [162.  54.   0.]
 [  0.  81.   0.]
 [ 27.  81.   0.]
 [ 54.  81.   0.]
 [ 81.  81.   0.]
 [108.  81.   0.]
 [135.  81.   0.]
 [162.  81.   0.]
 [  0. 108.   0.]
 [ 27. 108.   0.]
 [ 54. 108.   0.]
 [ 81. 108.   0.]
 [108. 108.   0.]
 [135. 108.   0.]
 [162. 108.   0.]
 [  0. 135.   0.]
 [ 27. 135.   0.]
 [ 54. 135.   0.]
 [ 81. 135.   0.]
 [108. 135.   0.]
 [135. 135.   0.]
 [162. 135.   0.]
 [  0. 162.   0.]
 [ 27. 162.   0.]
 [ 54. 162.   0.]
 [ 81. 162.   0.]
 [108. 162.   0.]
 [135. 162.   0.]
 [162. 162.   0.]]


In [6]:
findChessboardFlags = None
downScaleSize = (640,480)
# font
font = cv2.FONT_HERSHEY_SIMPLEX
# org
org = (50, 50)
# fontScale
fontScale = 1
# Blue color in BGR
color = (255, 0, 0)
# Line thickness of 2 px
thickness = 2

## Right cam calibration

In [7]:
imgRightPoints = []
objRightPoints = []

j=0
while(j<sizeR):
    imageSize = imgRList[j].shape
    rightFound, rightCorners = cv2.findChessboardCorners(imgRList[j], patternSize, flags = findChessboardFlags)
    
    if rightFound:
        cv2.cornerSubPix(imgRList[j], rightCorners, (11,11), (-1,-1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1))
        imgRightPoints.append(rightCorners)
        objRightPoints.append(objp)
    #endif

    cv2.drawChessboardCorners(imgRList[j], patternSize, rightCorners, rightFound)
    cv2.putText(imgRList[j], f'{j}/{sizeR}', org, font, fontScale, color, thickness, cv2.LINE_AA)
    #cv2.waitKey(300)
    cv2.imshow(f'r chess', cv2.resize(imgRList[j], downScaleSize))
    cv2.waitKey(200)
    j+=1
#endwhile
cv2.destroyAllWindows()

QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion


Error: Canceled future for execute_request message before replies were done

In [9]:
print(len(imgRightPoints))
print(len(objRightPoints))

23
23


In [10]:
# objRightPoints[0].type()
retR, mtxR, distR, rvecsR, tvecsR = cv2.calibrateCamera(
    objRightPoints,
    imgRightPoints,
    imgRList[0].shape[::-1],
    None,None
)

hR,wR = imgRList[0].shape[:2]
OmtxR, roiR = cv2.getOptimalNewCameraMatrix(mtxR, distR, (wR,hR), 1, (wR,hR))
print('mean reprojection error - right: ', retR)
print("roiR: ", roiR)

mean reprojection error - right:  0.45396938347500965
roiR:  (346, 185, 955, 840)


In [11]:
img = imgRList[25].copy()
# using cv2.undistort
dst = cv2.undistort(img, mtxR, distR, None, OmtxR)
x,y,w,h = roiR
dst = dst[y:y+h, x:x+w]

# using remapping
rightMap = cv2.initUndistortRectifyMap(mtxR, distR, None, OmtxR, img.shape[::-1], cv2.CV_16SC2)
rdst = cv2.remap(img,rightMap[0],rightMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
x,y,w,h = roiR
rdst = rdst[y:y+h, x:x+w]

cv2.imshow('undist', cv2.resize(dst, downScaleSize))
cv2.imshow('rundist', cv2.resize(rdst, downScaleSize))
cv2.imshow('img', cv2.resize(img, downScaleSize))
cv2.waitKey(0)
cv2.destroyAllWindows()

## Left cam calibration

In [12]:
imgLeftPoints = []
objLeftPoints = []

j=0
while(j<sizeL):
    imageSize = imgLList[j].shape
    leftFound, leftCorners = cv2.findChessboardCorners(imgLList[j], patternSize, flags = findChessboardFlags)
    
    if leftFound:
        cv2.cornerSubPix(imgLList[j], leftCorners, (11,11), (-1,-1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1))
        imgLeftPoints.append(leftCorners)
        objLeftPoints.append(objp)
    #endif

    cv2.drawChessboardCorners(imgLList[j], patternSize, leftCorners, leftFound)
    cv2.putText(imgLList[j], f'{j}/{sizeL}', org, font, fontScale, color, thickness, cv2.LINE_AA)
    #cv2.waitKey(300)
    cv2.imshow(f'l chess', cv2.resize(imgLList[j], downScaleSize))
    cv2.waitKey(200)
    j+=1
#endwhile
cv2.destroyAllWindows()

In [13]:
print(len(imgLeftPoints))
print(len(objLeftPoints))

20
20


In [14]:
retL, mtxL, distL, rvecsL, tvecsL = cv2.calibrateCamera(
    objLeftPoints,
    imgLeftPoints,
    imgLList[0].shape[::-1],
    None,None
)

hL,wL = imgLList[0].shape[:2]
OmtxL, roiL = cv2.getOptimalNewCameraMatrix(mtxL, distL, (wL,hL), 1, (wL,hL))
print('mean reprojection error - left: ', retL)
print("roiL: ", roiL)

mean reprojection error - left:  0.42556934052755035
roiL:  (317, 182, 1007, 835)


In [15]:
img = imgLList[1].copy()
# using cv2.undistort
dst = cv2.undistort(img, mtxL, distL, None, OmtxL)
x,y,w,h = roiL
dst = dst[y:y+h, x:x+w]

# using remapping
leftMap = cv2.initUndistortRectifyMap(mtxL, distL, None, OmtxL, img.shape[::-1], cv2.CV_16SC2)
ldst = cv2.remap(img,leftMap[0],leftMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
x,y,w,h = roiL
ldst = ldst[y:y+h, x:x+w]

cv2.imshow('undist', cv2.resize(dst, downScaleSize))
cv2.imshow('rundist', cv2.resize(ldst, downScaleSize))
cv2.imshow('img', cv2.resize(img, downScaleSize))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
formatm = [["fx","0","cx"],["0","fy","cy"],["0","0","1"]]
print('\n format -> \n',formatm)
print('\n mtxR -> \n',mtxR,2*'\n','OmtxR -> \n',OmtxR,2*'\n','mtxL -> \n',mtxL,2*'\n','OmtxL -> \n',OmtxL)


 format -> 
 [['fx', '0', 'cx'], ['0', 'fy', 'cy'], ['0', '0', '1']]

 mtxR -> 
 [[882.09909671   0.         804.02747442]
 [  0.         892.74988953 623.96069536]
 [  0.           0.           1.        ]] 

 OmtxR -> 
 [[526.71691895   0.         826.17698349]
 [  0.         625.07714844 621.7586973 ]
 [  0.           0.           1.        ]] 

 mtxL -> 
 [[859.7605329    0.         810.69078441]
 [  0.         868.8451415  599.75022877]
 [  0.           0.           1.        ]] 

 OmtxL -> 
 [[540.90814209   0.         827.34209175]
 [  0.         604.84527588 599.73413412]
 [  0.           0.           1.        ]]


## Stereo cam calibration

In [80]:
sizeStR = size(os.listdir(pathStR))
sizeStL = size(os.listdir(pathStL))

offset = 9
listingsStR = []
for i in range(offset+0, offset+sizeStR):
    listingsStR.append(f'{i}_R_.png')
#endfor

listingsStL = []
for i in range(offset+0, offset+sizeStL):
    listingsStL.append(f'{i}_L_.png')
#endfor

print(sizeStR, sizeStL)
print(listingsStR, listingsStL)

print("\nAfter shuffle:\n")
temp = list(zip(listingsStR, listingsStL))
random.shuffle(temp)
listingsStR, listingsStL = zip(*temp)
print(listingsStR, listingsStL)

12 12
['9_R_.png', '10_R_.png', '11_R_.png', '12_R_.png', '13_R_.png', '14_R_.png', '15_R_.png', '16_R_.png', '17_R_.png', '18_R_.png', '19_R_.png', '20_R_.png'] ['9_L_.png', '10_L_.png', '11_L_.png', '12_L_.png', '13_L_.png', '14_L_.png', '15_L_.png', '16_L_.png', '17_L_.png', '18_L_.png', '19_L_.png', '20_L_.png']

After shuffle:

('19_R_.png', '11_R_.png', '20_R_.png', '14_R_.png', '17_R_.png', '12_R_.png', '15_R_.png', '9_R_.png', '13_R_.png', '10_R_.png', '16_R_.png', '18_R_.png') ('19_L_.png', '11_L_.png', '20_L_.png', '14_L_.png', '17_L_.png', '12_L_.png', '15_L_.png', '9_L_.png', '13_L_.png', '10_L_.png', '16_L_.png', '18_L_.png')


In [81]:
imgStRList = []
i = 0
while(i<sizeStR):
    imStR = cv2.imread(pathStR+listingsStR[i], 0)
    imgStRList.append(imStR)
    i+=1
#endwhile
print(len(imgStRList))

imgStLList = []
i = 0
while(i<sizeStL):
    imStL = cv2.imread(pathStL+listingsStL[i], 0)
    imgStLList.append(imStL)
    i+=1
#endwhile
print(len(imgStLList))

print(imgStRList[0].shape)
print(imgStLList[0].shape)

12
12
(1200, 1600)
(1200, 1600)


In [82]:
chessSqSize = 27
h, w = 7,7
patternSize = (h,w)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((w*h,3), np.float32)
objp[:,:2] = np.mgrid[0:h,0:w].T.reshape(-1,2)*chessSqSize
print(objp)

[[  0.   0.   0.]
 [ 27.   0.   0.]
 [ 54.   0.   0.]
 [ 81.   0.   0.]
 [108.   0.   0.]
 [135.   0.   0.]
 [162.   0.   0.]
 [  0.  27.   0.]
 [ 27.  27.   0.]
 [ 54.  27.   0.]
 [ 81.  27.   0.]
 [108.  27.   0.]
 [135.  27.   0.]
 [162.  27.   0.]
 [  0.  54.   0.]
 [ 27.  54.   0.]
 [ 54.  54.   0.]
 [ 81.  54.   0.]
 [108.  54.   0.]
 [135.  54.   0.]
 [162.  54.   0.]
 [  0.  81.   0.]
 [ 27.  81.   0.]
 [ 54.  81.   0.]
 [ 81.  81.   0.]
 [108.  81.   0.]
 [135.  81.   0.]
 [162.  81.   0.]
 [  0. 108.   0.]
 [ 27. 108.   0.]
 [ 54. 108.   0.]
 [ 81. 108.   0.]
 [108. 108.   0.]
 [135. 108.   0.]
 [162. 108.   0.]
 [  0. 135.   0.]
 [ 27. 135.   0.]
 [ 54. 135.   0.]
 [ 81. 135.   0.]
 [108. 135.   0.]
 [135. 135.   0.]
 [162. 135.   0.]
 [  0. 162.   0.]
 [ 27. 162.   0.]
 [ 54. 162.   0.]
 [ 81. 162.   0.]
 [108. 162.   0.]
 [135. 162.   0.]
 [162. 162.   0.]]


In [83]:
imgStLeftPoints = []
imgStRightPoints = []
objStPoints = []

j=0
while(j<sizeStR):
    # print(j)
    imageSize = imgStLList[j].shape

    leftFound, leftCorners = cv2.findChessboardCorners(imgStLList[j], patternSize, flags = findChessboardFlags)
    rightFound, rightCorners = cv2.findChessboardCorners(imgStRList[j], patternSize, flags = findChessboardFlags)

    if leftFound:
        cv2.cornerSubPix(imgStLList[j], leftCorners, (11,11), (-1,-1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1))
    #endif

    if rightFound:
        cv2.cornerSubPix(imgStRList[j], rightCorners, (11,11), (-1,-1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1))
    #endif

    if leftFound and rightFound:
        imgStLeftPoints.append(leftCorners)
        imgStRightPoints.append(rightCorners)
        objStPoints.append(objp)
    #endif

    cv2.drawChessboardCorners(imgStLList[j], patternSize, leftCorners, leftFound)
    cv2.drawChessboardCorners(imgStRList[j], patternSize, rightCorners, rightFound)
    cv2.putText(imgStLList[j], f'{j}/{sizeStL}', org, font, fontScale, color, thickness, cv2.LINE_AA)
    cv2.putText(imgStRList[j], f'{j}/{sizeStR}', org, font, fontScale, color, thickness, cv2.LINE_AA)

    cv2.imshow("stl chess", cv2.resize(imgStLList[j], downScaleSize))
    cv2.imshow("str chess", cv2.resize(imgStRList[j], downScaleSize))
    cv2.waitKey(200)
    j+=1
#endwhile

cv2.destroyAllWindows()

In [84]:
cv2.destroyAllWindows()

In [85]:
print(len(imgStLeftPoints))
print(len(imgStRightPoints))

4
4


In [86]:
# stCriteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1)
stCriteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.0001)
stFlags = cv2.CALIB_FIX_ASPECT_RATIO | cv2.CALIB_ZERO_TANGENT_DIST | cv2.CALIB_SAME_FOCAL_LENGTH | cv2.CALIB_RATIONAL_MODEL | cv2.CALIB_FIX_K3 | cv2.CALIB_FIX_K4 | cv2.CALIB_FIX_K5
# stFlags = cv2.CALIB_FIX_INTRINSIC
retS, MLS, dLS, MRS, dRS, R, T, E, F = cv2.stereoCalibrate(
    objStPoints,
    imgStLeftPoints,
    imgStRightPoints,
    mtxL,
    distL,
    mtxR,
    distR,
    imStR.shape[::-1],
    stCriteria,
    stFlags
)

print('mean reprojection error - stereo ', retS)
print(' MRS -> ',MRS,2*'\n','mtxR -> ',mtxR,2*'\n','MLS -> ',MLS,2*'\n','mtxL -> ',mtxL)
print(' Rotational -> \n',R,2*'\n','Translational -> \n',T,2*'\n','Essential -> \n',E,2*'\n','Fundamental -> \n',F)

mean reprojection error - stereo  0.6540944502144848
 MRS ->  [[882.09909671   0.         804.02747442]
 [  0.         892.74988953 623.96069536]
 [  0.           0.           1.        ]] 

 mtxR ->  [[882.09909671   0.         804.02747442]
 [  0.         892.74988953 623.96069536]
 [  0.           0.           1.        ]] 

 MLS ->  [[859.7605329    0.         810.69078441]
 [  0.         868.8451415  599.75022877]
 [  0.           0.           1.        ]] 

 mtxL ->  [[859.7605329    0.         810.69078441]
 [  0.         868.8451415  599.75022877]
 [  0.           0.           1.        ]]
 Rotational -> 
 [[ 0.9998516  -0.01284173 -0.01148378]
 [ 0.01247694  0.99943239 -0.03129264]
 [ 0.01187912  0.03114471  0.99944429]] 

 Translational -> 
 [[314.80015321]
 [ -1.39355281]
 [ 21.92298694]] 

 Essential -> 
 [[-2.90085926e-01 -2.19539450e+01 -7.06750236e-01]
 [ 1.81801858e+01 -1.00858901e+01 -3.14876975e+02]
 [ 5.32108801e+00  3.14603573e+02 -9.86693151e+00]] 

 Fundamental ->

In [ ]:
np.save(calibParams+'R.npy', R)
np.save(calibParams+'T.npy', T)
np.save(calibParams+'E.npy', E)
np.save(calibParams+'F.npy', F)

np.save(calibParams+'MLS.npy', MLS)
np.save(calibParams+'dLS.npy', dLS)
np.save(calibParams+'MRS.npy', MRS)
np.save(calibParams+'dRS.npy', dRS)

In [87]:
rectifyScale = 0 # if 0 image croped, if 1 image nor croped
RL, RR, PL, PR, Q, roiL, roiR = cv2.stereoRectify(MLS, dLS, MRS, dRS, imStR.shape[::-1], R, T, rectifyScale) # last paramater is alpha, if 0= croped, if 1= not croped
# initUndistortRectifyMap function
leftStereoMap = cv2.initUndistortRectifyMap(MLS, dLS, RL, PL, imStL.shape[::-1], cv2.CV_16SC2)   # cv2.CV_16SC2 this format enables us the programme to work faster
rightStereoMap = cv2.initUndistortRectifyMap(MRS, dRS, RR, PR, imStR.shape[::-1], cv2.CV_16SC2)

In [ ]:
np.save(calibParams+'RL.npy', RL)
np.save(calibParams+'RR.npy', RR)
np.save(calibParams+'PL.npy', PL)
np.save(calibParams+'PR.npy', PR)
np.save(calibParams+'Q.npy', Q)

In [54]:
def drawLines(img):
    y,count = 0,0
    while(count<40):
        img = cv2.line(img, (0,50+y), (img.shape[1],50+y), (y,count*2,y), 2)
        y+=30
        count+=1
    #endwhile
    return cv2.resize(img, (640,480))
#enddef

In [88]:
picNum = '19'
rectPath = "../rectified/"
frameL = cv2.imread(pathStL+picNum+'_L_.png')
frameR = cv2.imread(pathStR+picNum+'_R_.png')

leftNice = cv2.remap(frameL,leftStereoMap[0],leftStereoMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)  # Rectify the image using the kalibration parameters founds during the initialisation
rightNice = cv2.remap(frameR,rightStereoMap[0],rightStereoMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)

frameLCpy = frameL.copy()
frameRCpy = frameR.copy()

xr,yr,wr,hr = roiR
xl,yl,wl,hl = roiL

rightImgRemapCp = rightNice.copy()
leftImgRemapCp = leftNice.copy()

cv2.imshow('R', drawLines(frameRCpy))
cv2.imshow('L', drawLines(frameLCpy))
cv2.imshow('R rect', drawLines(rightImgRemapCp))
cv2.imshow('L rect', drawLines(leftImgRemapCp))
cv2.waitKey(0)

origLR = np.concatenate((frameLCpy, frameRCpy), axis=1)
cv2.imwrite(rectPath+picNum+'_orig.png', origLR)
rectLR = np.concatenate((leftImgRemapCp, rightImgRemapCp), axis=1)
cv2.imwrite(rectPath+picNum+'_rect.png', rectLR)
cv2.destroyAllWindows()