In [1]:
import cv2
from numpy import *
import numpy as np
import os
import random

In [11]:
pathR = "../right/"
pathL = "../left/"

pathStR = "../both/right/"
pathStL = "../both/left/"

pathTestR = "../test/right/"
pathTestL = "../test/left/"

calibParams = "./calibParams/"

## Fetching images of individual cam

In [12]:
sizeR = size(os.listdir(pathR))
sizeL = size(os.listdir(pathL))

offset = 0
listingsR = []
for i in range(offset+0, offset+sizeR):
    listingsR.append(f'{i}_R_.png')
#endfor

listingsL = []
for i in range(offset+0, offset+sizeL):
    listingsL.append(f'{i}_L_.png')
#endfor

print(sizeR, sizeL)
print(listingsR, listingsL)

print("\nAfter shuffle:\n")
random.shuffle(listingsR)
random.shuffle(listingsL)
print(listingsR, listingsL)

79 80
['0_R_.png', '1_R_.png', '2_R_.png', '3_R_.png', '4_R_.png', '5_R_.png', '6_R_.png', '7_R_.png', '8_R_.png', '9_R_.png', '10_R_.png', '11_R_.png', '12_R_.png', '13_R_.png', '14_R_.png', '15_R_.png', '16_R_.png', '17_R_.png', '18_R_.png', '19_R_.png', '20_R_.png', '21_R_.png', '22_R_.png', '23_R_.png', '24_R_.png', '25_R_.png', '26_R_.png', '27_R_.png', '28_R_.png', '29_R_.png', '30_R_.png', '31_R_.png', '32_R_.png', '33_R_.png', '34_R_.png', '35_R_.png', '36_R_.png', '37_R_.png', '38_R_.png', '39_R_.png', '40_R_.png', '41_R_.png', '42_R_.png', '43_R_.png', '44_R_.png', '45_R_.png', '46_R_.png', '47_R_.png', '48_R_.png', '49_R_.png', '50_R_.png', '51_R_.png', '52_R_.png', '53_R_.png', '54_R_.png', '55_R_.png', '56_R_.png', '57_R_.png', '58_R_.png', '59_R_.png', '60_R_.png', '61_R_.png', '62_R_.png', '63_R_.png', '64_R_.png', '65_R_.png', '66_R_.png', '67_R_.png', '68_R_.png', '69_R_.png', '70_R_.png', '71_R_.png', '72_R_.png', '73_R_.png', '74_R_.png', '75_R_.png', '76_R_.png', '7

In [13]:
imgRList = []
i = 0
while(i<sizeR):
    imR = cv2.imread(pathR+listingsR[i])
    imgRList.append(imR)
    i+=1
#endwhile
print(len(imgRList))

imgLList = []
i = 0
while(i<sizeL):
    imL = cv2.imread(pathL+listingsL[i])
    imgLList.append(imL)
    i+=1
#endwhile
print(len(imgLList))

if len(imgRList) > 0:
    print(imgRList[0].shape)
#endif

if len(imgLList) > 0:
    print(imgLList[0].shape)
#endif

79
80
(1200, 1600, 3)
(1200, 1600, 3)


In [5]:
chessSqSize = 27
h, w = 7, 6
patternSize = (h,w)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((w*h,3), np.float32)
objp[:,:2] = np.mgrid[0:h,0:w].T.reshape(-1,2)*chessSqSize
print(objp)

chessCriteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 26, 0.001)
findChessboardFlags = None
downScaleSize = (640,480)
# font
font = cv2.FONT_HERSHEY_SIMPLEX
# org
org = (50, 50)
# fontScale
fontScale = 1
# Blue color in BGR
color = (255, 100, 50)
# Line thickness of 2 px
thickness = 2

[[  0.   0.   0.]
 [ 27.   0.   0.]
 [ 54.   0.   0.]
 [ 81.   0.   0.]
 [108.   0.   0.]
 [135.   0.   0.]
 [162.   0.   0.]
 [  0.  27.   0.]
 [ 27.  27.   0.]
 [ 54.  27.   0.]
 [ 81.  27.   0.]
 [108.  27.   0.]
 [135.  27.   0.]
 [162.  27.   0.]
 [  0.  54.   0.]
 [ 27.  54.   0.]
 [ 54.  54.   0.]
 [ 81.  54.   0.]
 [108.  54.   0.]
 [135.  54.   0.]
 [162.  54.   0.]
 [  0.  81.   0.]
 [ 27.  81.   0.]
 [ 54.  81.   0.]
 [ 81.  81.   0.]
 [108.  81.   0.]
 [135.  81.   0.]
 [162.  81.   0.]
 [  0. 108.   0.]
 [ 27. 108.   0.]
 [ 54. 108.   0.]
 [ 81. 108.   0.]
 [108. 108.   0.]
 [135. 108.   0.]
 [162. 108.   0.]
 [  0. 135.   0.]
 [ 27. 135.   0.]
 [ 54. 135.   0.]
 [ 81. 135.   0.]
 [108. 135.   0.]
 [135. 135.   0.]
 [162. 135.   0.]]


## Right cam calibration

In [6]:
imgRightPoints = []
objRightPoints = []
rightImage = None
rightImageGray = None
j=0
while(j<sizeR):
    print(f'getting: {j}...')
    imageSize = imgRList[j].shape
    rightImageGray = cv2.cvtColor(imgRList[j], cv2.COLOR_BGR2GRAY)
    rightImage = imgRList[j].copy()
    rightFound, rightCorners = cv2.findChessboardCorners(rightImageGray, patternSize, flags = findChessboardFlags)
    
    if rightFound:
        cv2.cornerSubPix(rightImageGray, rightCorners, (11,11), (-1,-1), chessCriteria)
        print(f'{str(rightFound)}: {j}')
    #endif

    cv2.drawChessboardCorners(rightImage, patternSize, rightCorners, rightFound)
    cv2.putText(rightImage, f'{j}/{sizeR}', org, font, fontScale, color, thickness, cv2.LINE_AA)

    if rightFound:
        cv2.putText(rightImage, 'Press a to accept, any other key to reject.', (50, 150), font, fontScale, color, thickness, cv2.LINE_AA)
        cv2.imshow(f'r chess', cv2.resize(rightImage, downScaleSize))
        if cv2.waitKey(0) & 0xff == ord('a'):
            imgRightPoints.append(rightCorners)
            objRightPoints.append(objp)
            print(f'accepted: {j}')
        else:
            cv2.waitKey(200)
            print(f'rejected: {j}')
        #endif
    else:
        cv2.imshow(f'r chess', cv2.resize(rightImage, downScaleSize))
        cv2.waitKey(200)
        print(f'auto rejected: {j}')
    #endif

    print('...........................')

    j+=1
#endwhile
cv2.destroyAllWindows()

getting: 0...
True: 0


QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion


accepted: 0
...........................
getting: 1...
True: 1
accepted: 1
...........................
getting: 2...
True: 2
accepted: 2
...........................
getting: 3...
True: 3
rejected: 3
...........................
getting: 4...
True: 4
accepted: 4
...........................
getting: 5...
True: 5
accepted: 5
...........................
getting: 6...
True: 6
accepted: 6
...........................
getting: 7...
True: 7
accepted: 7
...........................
getting: 8...
True: 8
accepted: 8
...........................
getting: 9...
True: 9
accepted: 9
...........................
getting: 10...
True: 10
accepted: 10
...........................
getting: 11...
True: 11
accepted: 11
...........................
getting: 12...
True: 12
rejected: 12
...........................
getting: 13...
True: 13
accepted: 13
...........................
getting: 14...
True: 14
accepted: 14
...........................
getting: 15...
True: 15
accepted: 15
...........................
getting: 16.

In [ ]:
cv2.destroyAllWindows()
print(len(imgRightPoints))
print(len(objRightPoints))

In [8]:
# objRightPoints[0].type()
retR, mtxR, distR, rvecsR, tvecsR = cv2.calibrateCamera(
    objRightPoints,
    imgRightPoints,
    rightImageGray.shape[::-1],
    None,None
)

hR,wR = rightImageGray.shape[:2]
OmtxR, roiR = cv2.getOptimalNewCameraMatrix(mtxR, distR, (wR,hR), 1, (wR,hR))
print('ret - right: ', retR)
print("roiR: ", roiR)

# https://docs.opencv.org/4.5.4/dc/dbb/tutorial_py_calibration.html
meanRightError = 0
for i in range(len(objRightPoints)):
    imgRightPoints2, _ = cv2.projectPoints(objRightPoints[i], rvecsR[i], tvecsR[i], mtxR, distR)
    error = cv2.norm(imgRightPoints[i], imgRightPoints2, cv2.NORM_L2)/len(imgRightPoints2)
    meanRightError += error
#endfor

print("Total reprojection error: {}".format(meanRightError/len(objRightPoints)))

ret - right:  0.4455011793860717
roiR:  (285, 192, 983, 830)
Total reprojection error: 0.043254537558807295


In [10]:
img = cv2.cvtColor(imgRList[20], cv2.COLOR_BGR2GRAY)
# using cv2.undistort
dst = cv2.undistort(img, mtxR, distR, None, OmtxR)
x,y,w,h = roiR
dst = dst[y:y+h, x:x+w]

# using remapping
rightMap = cv2.initUndistortRectifyMap(mtxR, distR, None, OmtxR, img.shape[::-1], cv2.CV_16SC2)
rdst = cv2.remap(img,rightMap[0],rightMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
x,y,w,h = roiR
rdst = rdst[y:y+h, x:x+w]

cv2.imshow('undist', cv2.resize(dst, downScaleSize))
cv2.imshow('rundist', cv2.resize(rdst, downScaleSize))
cv2.imshow('img', cv2.resize(img, downScaleSize))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.destroyAllWindows()

## Left cam calibration

In [14]:
imgLeftPoints = []
objLeftPoints = []
leftImage = None
leftImageGray = None

j=0
while(j<sizeL):
    print(f'getting: {j}...')
    imageSize = imgLList[j].shape
    leftImageGray = cv2.cvtColor(imgLList[j], cv2.COLOR_BGR2GRAY)
    leftImage = imgLList[j].copy()
    leftFound, leftCorners = cv2.findChessboardCorners(leftImageGray, patternSize, flags = findChessboardFlags)
    
    if leftFound:
        cv2.cornerSubPix(leftImageGray, leftCorners, (11,11), (-1,-1), chessCriteria)
        print(f'{str(leftFound)}: {j}')
    #endif

    cv2.drawChessboardCorners(leftImage, patternSize, leftCorners, leftFound)
    cv2.putText(leftImage, f'{j}/{sizeL}', org, font, fontScale, color, thickness, cv2.LINE_AA)

    if leftFound:
        cv2.putText(leftImage, 'Press a to accept, any other key to reject.', (50, 150), font, fontScale, color, thickness, cv2.LINE_AA)
        cv2.imshow(f'l chess', cv2.resize(leftImage, downScaleSize))
        if cv2.waitKey(0) & 0xff == ord('a'):
            imgLeftPoints.append(leftCorners)
            objLeftPoints.append(objp)
            print(f'accepted: {j}')
        else:
            cv2.waitKey(200)
            print(f'rejected: {j}')
        #endif
    else:
        cv2.imshow(f'l chess', cv2.resize(leftImage, downScaleSize))
        cv2.waitKey(200)
        print(f'auto rejected: {j}')
    #endif

    print('...........................')

    j+=1
#endwhile
cv2.destroyAllWindows()

getting: 0...
True: 0
accepted: 0
...........................
getting: 1...
True: 1
accepted: 1
...........................
getting: 2...
True: 2
accepted: 2
...........................
getting: 3...
True: 3
rejected: 3
...........................
getting: 4...
True: 4
accepted: 4
...........................
getting: 5...
True: 5
accepted: 5
...........................
getting: 6...
True: 6
accepted: 6
...........................
getting: 7...
True: 7
rejected: 7
...........................
getting: 8...
True: 8
accepted: 8
...........................
getting: 9...
True: 9
accepted: 9
...........................
getting: 10...
True: 10
accepted: 10
...........................
getting: 11...
True: 11
rejected: 11
...........................
getting: 12...
True: 12
accepted: 12
...........................
getting: 13...
True: 13
accepted: 13
...........................
getting: 14...
True: 14
accepted: 14
...........................
getting: 15...
True: 15
accepted: 15
..................

In [15]:
cv2.destroyAllWindows()
print(len(imgLeftPoints))
print(len(objLeftPoints))

65
65


In [17]:
retL, mtxL, distL, rvecsL, tvecsL = cv2.calibrateCamera(
    objLeftPoints,
    imgLeftPoints,
    leftImageGray.shape[::-1],
    None,None
)

hL,wL = leftImageGray.shape[:2]
OmtxL, roiL = cv2.getOptimalNewCameraMatrix(mtxL, distL, (wL,hL), 1, (wL,hL))
print('ret - left: ', retL)
print("roiL: ", roiL)

meanLeftError = 0
for i in range(len(objLeftPoints)):
    imgLeftPoints2, _ = cv2.projectPoints(objLeftPoints[i], rvecsL[i], tvecsL[i], mtxL, distL)
    error = cv2.norm(imgLeftPoints[i], imgLeftPoints2, cv2.NORM_L2)/len(imgLeftPoints2)
    meanLeftError += error
print("Total reprojection error: {}".format(meanLeftError/len(objLeftPoints)) )

ret - left:  0.9325628818591054
roiL:  (164, 509, 555, 466)
Total reprojection error: 0.07002697104714883


In [19]:
img = cv2.cvtColor(imgLList[75], cv2.COLOR_BGR2GRAY)
# using cv2.undistort
dst = cv2.undistort(img, mtxL, distL, None, OmtxL)
x,y,w,h = roiL
dst = dst[y:y+h, x:x+w]

# using remapping
leftMap = cv2.initUndistortRectifyMap(mtxL, distL, None, OmtxL, img.shape[::-1], cv2.CV_16SC2)
ldst = cv2.remap(img,leftMap[0],leftMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)
x,y,w,h = roiL
ldst = ldst[y:y+h, x:x+w]

cv2.imshow('undist', cv2.resize(dst, downScaleSize))
cv2.imshow('rundist', cv2.resize(ldst, downScaleSize))
cv2.imshow('img', cv2.resize(img, downScaleSize))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
formatm = [["fx","0","cx"],["0","fy","cy"],["0","0","1"]]
print('\n format -> \n',formatm)
print('\n mtxR -> \n',mtxR,2*'\n','OmtxR -> \n',OmtxR,2*'\n','mtxL -> \n',mtxL,2*'\n','OmtxL -> \n',OmtxL)


 format -> 
 [['fx', '0', 'cx'], ['0', 'fy', 'cy'], ['0', '0', '1']]

 mtxR -> 
 [[865.01234245   0.         787.26088878]
 [  0.         865.54856289 601.19468339]
 [  0.           0.           1.        ]] 

 OmtxR -> 
 [[531.49023438   0.         768.26895233]
 [  0.         598.56591797 607.48032173]
 [  0.           0.           1.        ]] 

 mtxL -> 
 [[854.04143235   0.         814.66070348]
 [  0.         853.99709956 589.73557822]
 [  0.           0.           1.        ]] 

 OmtxL -> 
 [[296.04003906   0.         446.81178212]
 [  0.         331.5017395  737.57300239]
 [  0.           0.           1.        ]]


## Stereo cam calibration

In [21]:
sizeStR = size(os.listdir(pathStR))
sizeStL = size(os.listdir(pathStL))

offset = 0
listingsStR = []
for i in range(offset+0, offset+sizeStR):
    listingsStR.append(f'{i}_R_.png')
#endfor

listingsStL = []
for i in range(offset+0, offset+sizeStL):
    listingsStL.append(f'{i}_L_.png')
#endfor

print(sizeStR, sizeStL)
print(listingsStR, listingsStL)

print("\nAfter shuffle:\n")
temp = list(zip(listingsStR, listingsStL))
random.shuffle(temp)
listingsStR, listingsStL = zip(*temp)
print(listingsStR, listingsStL)

42 42
['0_R_.png', '1_R_.png', '2_R_.png', '3_R_.png', '4_R_.png', '5_R_.png', '6_R_.png', '7_R_.png', '8_R_.png', '9_R_.png', '10_R_.png', '11_R_.png', '12_R_.png', '13_R_.png', '14_R_.png', '15_R_.png', '16_R_.png', '17_R_.png', '18_R_.png', '19_R_.png', '20_R_.png', '21_R_.png', '22_R_.png', '23_R_.png', '24_R_.png', '25_R_.png', '26_R_.png', '27_R_.png', '28_R_.png', '29_R_.png', '30_R_.png', '31_R_.png', '32_R_.png', '33_R_.png', '34_R_.png', '35_R_.png', '36_R_.png', '37_R_.png', '38_R_.png', '39_R_.png', '40_R_.png', '41_R_.png'] ['0_L_.png', '1_L_.png', '2_L_.png', '3_L_.png', '4_L_.png', '5_L_.png', '6_L_.png', '7_L_.png', '8_L_.png', '9_L_.png', '10_L_.png', '11_L_.png', '12_L_.png', '13_L_.png', '14_L_.png', '15_L_.png', '16_L_.png', '17_L_.png', '18_L_.png', '19_L_.png', '20_L_.png', '21_L_.png', '22_L_.png', '23_L_.png', '24_L_.png', '25_L_.png', '26_L_.png', '27_L_.png', '28_L_.png', '29_L_.png', '30_L_.png', '31_L_.png', '32_L_.png', '33_L_.png', '34_L_.png', '35_L_.png'

In [22]:
imgStRList = []
i = 0
while(i<sizeStR):
    imStR = cv2.imread(pathStR+listingsStR[i])
    imgStRList.append(imStR)
    i+=1
#endwhile
print(len(imgStRList))

imgStLList = []
i = 0
while(i<sizeStL):
    imStL = cv2.imread(pathStL+listingsStL[i])
    imgStLList.append(imStL)
    i+=1
#endwhile
print(len(imgStLList))

print(imgStRList[0].shape)
print(imgStLList[0].shape)

42
42
(1200, 1600, 3)
(1200, 1600, 3)


In [23]:
chessSqSize = 27
h, w = 7,6
patternSize = (h,w)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((w*h,3), np.float32)
objp[:,:2] = np.mgrid[0:h,0:w].T.reshape(-1,2)*chessSqSize
print(objp)

chessCriteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 26, 0.001)
findChessboardFlags = None
downScaleSize = (640,480)
# font
font = cv2.FONT_HERSHEY_SIMPLEX
# org
org = (50, 50)
# fontScale
fontScale = 1
# Blue color in BGR
color = (55, 10, 100)
# Line thickness of 2 px
thickness = 2

[[  0.   0.   0.]
 [ 27.   0.   0.]
 [ 54.   0.   0.]
 [ 81.   0.   0.]
 [108.   0.   0.]
 [135.   0.   0.]
 [162.   0.   0.]
 [  0.  27.   0.]
 [ 27.  27.   0.]
 [ 54.  27.   0.]
 [ 81.  27.   0.]
 [108.  27.   0.]
 [135.  27.   0.]
 [162.  27.   0.]
 [  0.  54.   0.]
 [ 27.  54.   0.]
 [ 54.  54.   0.]
 [ 81.  54.   0.]
 [108.  54.   0.]
 [135.  54.   0.]
 [162.  54.   0.]
 [  0.  81.   0.]
 [ 27.  81.   0.]
 [ 54.  81.   0.]
 [ 81.  81.   0.]
 [108.  81.   0.]
 [135.  81.   0.]
 [162.  81.   0.]
 [  0. 108.   0.]
 [ 27. 108.   0.]
 [ 54. 108.   0.]
 [ 81. 108.   0.]
 [108. 108.   0.]
 [135. 108.   0.]
 [162. 108.   0.]
 [  0. 135.   0.]
 [ 27. 135.   0.]
 [ 54. 135.   0.]
 [ 81. 135.   0.]
 [108. 135.   0.]
 [135. 135.   0.]
 [162. 135.   0.]]


In [24]:
imgStLeftPoints = []
imgStRightPoints = []
objStPoints = []
stRightImage, stLeftImage, stRightImageGray, stLeftImageGray = None,None,None,None

j=0
while(j<sizeStR):
    print(f'getting: {j}...')
    imageSize = imgStLList[j].shape

    stLeftImageGray = cv2.cvtColor(imgStLList[j], cv2.COLOR_BGR2GRAY)
    stLeftImage = imgStLList[j].copy()
    stRightImageGray = cv2.cvtColor(imgStRList[j], cv2.COLOR_BGR2GRAY)
    stRightImage = imgStRList[j].copy()

    leftFound, leftCorners = cv2.findChessboardCorners(stLeftImageGray, patternSize, flags = findChessboardFlags)
    rightFound, rightCorners = cv2.findChessboardCorners(stRightImageGray, patternSize, flags = findChessboardFlags)

    if leftFound:
        cv2.cornerSubPix(stLeftImageGray, leftCorners, (11,11), (-1,-1), chessCriteria)
        print(f'Left = {str(leftFound)}: {j}')
    #endif

    if rightFound:
        cv2.cornerSubPix(stRightImageGray, rightCorners, (11,11), (-1,-1), chessCriteria)
        print(f'Right = {str(leftFound)}: {j}')
    #endif

    cv2.drawChessboardCorners(stLeftImage, patternSize, leftCorners, leftFound)
    cv2.drawChessboardCorners(stRightImage, patternSize, rightCorners, rightFound)
    cv2.putText(stLeftImage, f'{j}/{sizeStL}', org, font, fontScale, color, thickness, cv2.LINE_AA)
    cv2.putText(stRightImage, f'{j}/{sizeStR}', org, font, fontScale, color, thickness, cv2.LINE_AA)


    if leftFound and rightFound:
        cv2.putText(stLeftImage, 'Press a to accept, any other key to reject.', (50, 150), font, fontScale, color, thickness, cv2.LINE_AA)
        cv2.putText(stRightImage, 'Press a to accept, any other key to reject.', (50, 150), font, fontScale, color, thickness, cv2.LINE_AA)
        
        cv2.imshow("stl chess", cv2.resize(stLeftImage, downScaleSize))
        cv2.imshow("str chess", cv2.resize(stRightImage, downScaleSize))

        if cv2.waitKey(0) & 0xff == ord('a'):
            imgStLeftPoints.append(leftCorners)
            imgStRightPoints.append(rightCorners)
            objStPoints.append(objp)
            print(f'accepted: {j}')
        else:
            cv2.waitKey(200)
            print(f'rejected: {j}')
        #endif
    else:
        cv2.imshow("stl chess", cv2.resize(stLeftImage, downScaleSize))
        cv2.imshow("str chess", cv2.resize(stRightImage, downScaleSize))
        cv2.waitKey(200)
        print(f'auto rejected: {j}')
    #endif

    print('...........................')

    j+=1
#endwhile

cv2.destroyAllWindows()

getting: 0...
Left = True: 0
Right = True: 0
accepted: 0
...........................
getting: 1...
Left = True: 1
Right = True: 1
accepted: 1
...........................
getting: 2...
Left = True: 2
Right = True: 2
accepted: 2
...........................
getting: 3...
Left = True: 3
Right = True: 3
accepted: 3
...........................
getting: 4...
Left = True: 4
Right = True: 4
accepted: 4
...........................
getting: 5...
Right = False: 5
auto rejected: 5
...........................
getting: 6...
Left = True: 6
Right = True: 6
accepted: 6
...........................
getting: 7...
Left = True: 7
Right = True: 7
accepted: 7
...........................
getting: 8...
Right = False: 8
auto rejected: 8
...........................
getting: 9...
Left = True: 9
Right = True: 9
accepted: 9
...........................
getting: 10...
Left = True: 10
Right = True: 10
accepted: 10
...........................
getting: 11...
Left = True: 11
Right = True: 11
accepted: 11
..................

In [25]:
cv2.destroyAllWindows()

In [26]:
print(len(imgStLeftPoints))
print(len(imgStRightPoints))

34
34


In [27]:
# stCriteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1)
stCriteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.001)
# stFlags = cv2.CALIB_FIX_ASPECT_RATIO | cv2.CALIB_ZERO_TANGENT_DIST | cv2.CALIB_SAME_FOCAL_LENGTH | cv2.CALIB_RATIONAL_MODEL | cv2.CALIB_FIX_K3 | cv2.CALIB_FIX_K4 | cv2.CALIB_FIX_K5
stFlags = cv2.CALIB_FIX_INTRINSIC
retS, MLS, dLS, MRS, dRS, R, T, E, F = cv2.stereoCalibrate(
    objStPoints,
    imgStLeftPoints,
    imgStRightPoints,
    mtxL,
    distL,
    mtxR,
    distR,
    stLeftImageGray.shape[::-1],
    stCriteria,
    stFlags
)

print('ret - stereo ', retS)

print(' MRS -> ',MRS,2*'\n','mtxR -> ',mtxR,2*'\n','MLS -> ',MLS,2*'\n','mtxL -> ',mtxL)
print(' Rotational -> \n',R,2*'\n','Translational -> \n',T,2*'\n','Essential -> \n',E,2*'\n','Fundamental -> \n',F)

ret - stereo  0.9272042264235885
 MRS ->  [[865.01234245   0.         787.26088878]
 [  0.         865.54856289 601.19468339]
 [  0.           0.           1.        ]] 

 mtxR ->  [[865.01234245   0.         787.26088878]
 [  0.         865.54856289 601.19468339]
 [  0.           0.           1.        ]] 

 MLS ->  [[854.04143235   0.         814.66070348]
 [  0.         853.99709956 589.73557822]
 [  0.           0.           1.        ]] 

 mtxL ->  [[854.04143235   0.         814.66070348]
 [  0.         853.99709956 589.73557822]
 [  0.           0.           1.        ]]
 Rotational -> 
 [[ 9.99773608e-01  4.26290526e-05  2.12774798e-02]
 [ 3.78233756e-04  9.99804378e-01 -1.97753138e-02]
 [-2.12741604e-02  1.97788847e-02  9.99578014e-01]] 

 Translational -> 
 [[310.03114871]
 [ -1.00881436]
 [  9.28381869]] 

 Essential -> 
 [[ 1.79502250e-02 -9.30195579e+00 -8.24798229e-01]
 [ 1.58773693e+01 -6.13167458e+00 -3.09702784e+02]
 [ 1.12585022e+00  3.09970543e+02 -6.10949823e+00]] 


In [36]:
np.save(calibParams+'R.npy', R)
np.save(calibParams+'T.npy', T)
np.save(calibParams+'E.npy', E)
np.save(calibParams+'F.npy', F)

np.save(calibParams+'MLS.npy', MLS)
np.save(calibParams+'dLS.npy', dLS)
np.save(calibParams+'MRS.npy', MRS)
np.save(calibParams+'dRS.npy', dRS)

In [29]:
rectifyScale = 0 # if 0 image croped, if 1 image nor croped
RL, RR, PL, PR, Q, roiL, roiR = cv2.stereoRectify(MLS, dLS, MRS, dRS, stLeftImageGray.shape[::-1], R, T, rectifyScale) # last paramater is alpha, if 0= croped, if 1= not croped
# initUndistortRectifyMap function
leftStereoMap = cv2.initUndistortRectifyMap(MLS, dLS, RL, PL, stLeftImageGray.shape[::-1], cv2.CV_16SC2)   # cv2.CV_16SC2 this format enables us the programme to work faster
rightStereoMap = cv2.initUndistortRectifyMap(MRS, dRS, RR, PR, stRightImageGray.shape[::-1], cv2.CV_16SC2)

In [37]:
np.save(calibParams+'RL.npy', RL)
np.save(calibParams+'RR.npy', RR)
np.save(calibParams+'PL.npy', PL)
np.save(calibParams+'PR.npy', PR)
np.save(calibParams+'Q.npy', Q)

In [32]:
def drawLines(img):
    # img = image.copy()
    y,count = 0,0
    while(count<40):
        img = cv2.line(img, (0,50+y), (img.shape[1],50+y), (y,count*2,y), 2)
        y+=30
        count+=1
    #endwhile
    return cv2.resize(img, (640,480))
#enddef

In [45]:
picNum = '1'
rectPath = "../rectified/"
frameL = cv2.imread(pathTestL+picNum+'_L_.png')
frameR = cv2.imread(pathTestR+picNum+'_R_.png')

leftNice = cv2.remap(frameL,leftStereoMap[0],leftStereoMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)  # Rectify the image using the kalibration parameters founds during the initialisation
rightNice = cv2.remap(frameR,rightStereoMap[0],rightStereoMap[1], cv2.INTER_LANCZOS4, cv2.BORDER_CONSTANT, 0)

frameLCpy = frameL.copy()
frameRCpy = frameR.copy()

xr,yr,wr,hr = roiR
xl,yl,wl,hl = roiL

rightImgRemapCp = rightNice.copy()
leftImgRemapCp = leftNice.copy()

cv2.imshow('R', drawLines(frameRCpy))
cv2.imshow('L', drawLines(frameLCpy))
cv2.imshow('R rect', drawLines(rightImgRemapCp))
cv2.imshow('L rect', drawLines(leftImgRemapCp))
cv2.waitKey(0)

origLR = np.concatenate((frameLCpy, frameRCpy), axis=1)
cv2.imwrite(rectPath+picNum+'_orig.png', origLR)
rectLR = np.concatenate((leftImgRemapCp, rightImgRemapCp), axis=1)
cv2.imwrite(rectPath+picNum+'_rect.png', rectLR)
cv2.destroyAllWindows()

In [ ]:
grayR = cv2.cvtColor(rightNice,cv2.COLOR_BGR2GRAY)
grayL = cv2.cvtColor(leftNice,cv2.COLOR_BGR2GRAY)

# Create StereoSGBM and prepare all parameters
window_size = 7
min_disp = 1
num_disp = (16*16)+1-min_disp
left_matcher = cv2.StereoSGBM_create(minDisparity = min_disp,
    numDisparities = num_disp,
    blockSize = window_size,
    uniquenessRatio = 10,
    speckleWindowSize = 100,
    speckleRange = 32,
    disp12MaxDiff = 5,
    P1 = 8*3*window_size**2,
    P2 = 32*3*window_size**2)

# Used for the filtered image
right_matcher = cv2.ximgproc.createRightMatcher(left_matcher) # Create another stereo for right this time

# WLS FILTER Parameters
lmbda = 80000
sigma = 1.8
visual_multiplier = 1.0

wls_filter = cv2.ximgproc.createDisparityWLSFilter(matcher_left=left_matcher)
wls_filter.setLambda(lmbda)
wls_filter.setSigmaColor(sigma)

dispL = left_matcher.compute(grayL,grayR)
dispR = right_matcher.compute(grayR,grayL)
dispL = np.int16(dispL)
dispR = np.int16(dispR)

filteredImg = wls_filter.filter(dispL, grayL, None, dispR)  # important to put "imgL" here!!!
filteredImg = cv2.normalize(src=filteredImg, dst=filteredImg, beta=0, alpha=255, norm_type=cv2.NORM_MINMAX);
filteredImg = np.uint8(filteredImg)

fil = cv2.resize(filteredImg, (640, 480))
cv2.imshow('filteredImg',fil)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.destroyAllWindows()